global:
  domain: argocd.example.com

server:
  replicas: 1
  service:
    type: LoadBalancer

configs:
  params:
    server.insecure: true
  cm:
    accounts.ali: login
    accounts.ahmed: login
    accounts.rizwan: login
    accounts.adnan: login
    accounts.sonia: login
  rbac:
    policy.csv: |
      g, ali, role:admin
      g, ahmed, role:admin
      g, rizwan, role:admin
      g, adnan, role:admin
      g, sonia, role:admin